name: Git Action 12

on:
  schedule:
    - cron: '0 3 * * TUE'
  
jobs:

  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)
  
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependancies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Build
        run: npm run build