name: Git Action 10

on:
  schedule:
    - cron: '30 0-21/3 * * *'
    - cron: '30 1-22/3 * * *'
  
jobs:

  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)